server:
  port: 8080
  logpath: "your_log_path"
  assentpath: "your_assent_path"

database:
  enabled: true
  host: 127.0.0.1
  port: 3306
  username: root
  password: "yourpassword"
  name: mybbs
  
jwt:
  secret: "your_jwt_secret_key"
  expiration: 24